# ansys.meshing.prime.ErrorCode.MULTIZONEMESHER_NOVOLUMESSCOPEDINCURRENTPART

#### ErrorCode.MULTIZONEMESHER_NOVOLUMESSCOPEDINCURRENTPART *= 2613*

No volumes for geometry import in the current part.

<!-- !! processed by numpydoc !! -->
